lib/simple_form/components/labels.rb, test/form_builder/label_test.rb
Adds disabled class to the attribute label so that it might also be
styled when the input is disabled
=> Add disabled class to label's additional classes

README.md, lib/generators/simple_form/templates/config/initializers/simple_form.rb
Item_wrapper_tag configuration option in 3.x behaves independently, without any limitations imposed by nested boolean_style as mentioned in the documentation.
Update readme and a comment inside the initializer.
Closes #1224.
=> Update docs regarding item_wrapper_tag

lib/simple_form/inputs/boolean_input.rb
Fixes warning:
/home/badosu/.gem/ruby/2.2.1/gems/simple_form-2.1.2/lib/simple\
_form/inputs/boolean_input.rb:37:
warning: circular argument reference - unchecked_value
=> Fix method reflection for ruby 2.1

test/inputs/text_input_test.rb
In v3.1.0 I've run into a situation where i18n.t() is run twice on the placeholder.  This passes the existing tests because the output is matches:
`f.input :name, :placeholder => "User name"` will output 
```
<input name="user[name]" placeholder="User name">
``` 
It passes the current test suite but, oddly, this Ruby code will also pass: `f.input :name, :placeholder => "foo.bar.user name"`
It looks as though something is causing a situation like `I18n.t(I18n.t(placeholder))`
I think it may be the way `translate_from_namespace` is implemented combined with an interaction with this line: `placeholder.is_a?(String) ? placeholder : translate_from_namespace(:placeholders)`.  Perhaps placeholder has been assigned but isn't a String causing it to be run again.
=> New test to cover placeholder failure

lib/generators/simple_form/templates/config/initializers/simple_form_bootstrap.rb
correction to issue #1186
```ruby
config.wrappers :horizontal_select_date, tag: 'div', class: 'form-group', error_class: 'has-error' do |b|
b.use :html5
b.optional :readonly
b.use :label, class: 'control-label'
b.wrapper tag: 'div', class: 'form-inline' do |ba|
ba.use :input, class: 'form-control'
ba.use :error, wrap_with: { tag: 'span', class: 'help-block' }
ba.use :hint,  wrap_with: { tag: 'p', class: 'help-block' }
end
end
```
in html
```ruby
<%= f.input :date, wrapper: :horizontal_select_date %>
```
=> correction bootstrap datetime field, issue #1186 

CHANGELOG.md, lib/generators/simple_form/templates/config/initializers/simple_form_bootstrap.rb
Thanks for the PR https://github.com/plataformatec/simple_form/pull/1204 we now can have a nice style
for our datetime fields. I've just applied that format for date and time.
It closes #1186 
Now looks ok:
=> Apply nice format for datetime, date and time on bootstrap.

lib/simple_form/form_builder.rb, test/form_builder/general_test.rb
Hello everyone! I have the following configuration for my custom form fields:
```ruby
config.input_mappings = {/bodytype/ => :check_boxes}
```
And would like to provide my custom collection generation helper for this kind of input, like this:
```ruby
f.input :bodytype, :collection => bodytype_collection
````
But it doesn't work for me because of explicit return in `default_input_type` method, my quick and dirty solution was simple, bump custom time detection statements top. Is that an issue, or it is impossible to use :collection option by design?
=> Can't set collection for configured custom value input

lib/simple_form/components/html5.rb, test/inputs/required_test.rb, test/support/misc_helpers.rb
fixes #1178 
@jedschneider hey, I fixed you test and added it to this pull request.
=> Make it possible to override required value that was set in the wrapper.

lib/simple_form/form_builder.rb, lib/simple_form/inputs/collection_radio_buttons_input.rb
A tiny performance enhancement. Using symbol interpolation instead of strings is about 50% faster when being used with `#send`. The overall enhancement is very small since these methods are being called relatively rarely.
=> Use symbols instead of strings for #send

simple_form.gemspec
Hi @carlosantoniodasilva 
Just updated gemspec to support activemodel >= 4 && actionpack >= 4 to support rails edge version.
Please review and merge.
Thanks
=> Update gem dependency to support rails 5 alpha

lib/simple_form/form_builder.rb
I noticed that the functionality of the `#input` method when a block is given was undocumented. It would have saved 5-10 minutes of my time if it had been there before.
=> Add docs for #input method with block

README.md
From @rafaelfranca's StackOverflow answer here: http://stackoverflow.com/questions/6334582/simple-form-association-custom-label-name/6335679#6335679
This seems like fairly useful information and the comment below Rafael's seemed to indicate others would find it helpful in the docs also.
=> Add label_method info in README

README.md, lib/simple_form/components/html5.rb, test/form_builder/error_test.rb
Adds `aria-invalid` attribute to fields with errors. 
https://www.w3.org/TR/WCAG20-TECHS/ARIA21.html
=> Adds aria-invalid attribute to fields with errors

Gemfile, Gemfile.lock, lib/simple_form.rb, lib/simple_form/components/maxlength.rb, test/inputs/datetime_input_test.rb, test/inputs/discovery_test.rb, test/inputs/priority_input_test.rb, test/inputs/string_input_test.rb, test/support/models.rb
Enhancements
* Support to Rails `5.0.x` Stable.
Unreleased
* Removed deprecated methods `default_input_size`.
=> Add support Rails 5

lib/simple_form/action_view_extensions/builder.rb, lib/simple_form/action_view_extensions/form_helper.rb
this resolves a load order issue which I encountered when testing with rspec.
Also, the same problem occurred with https://github.com/bootstrap-ruby/rails-bootstrap-forms, which I solved in a similar manner in https://github.com/bootstrap-ruby/rails-bootstrap-forms/pull/275
=> only include ActionViewExtensions when ActionView is loaded

lib/simple_form/inputs/boolean_input.rb, test/inputs/boolean_input_test.rb
Give the possibility to skip the creation of the hidden input field
normally created along with checkox field, replicating [Rails 4.2 behavior](https://github.com/rails/rails/blob/4-2-stable/actionview/lib/action_view/helpers/tags/check_box.rb#L28)
=> Add `hidden_input` option to checkbox

lib/simple_form/form_builder.rb, test/form_builder/label_test.rb
=> Ignore the `:label_text` when rendering `label` tags.

CHANGELOG.md, lib/simple_form/inputs/base.rb, test/form_builder/wrapper_test.rb, test/support/misc_helpers.rb
As described in the #1278 issue modified the method of `merge_wrapper_options` to support duplicated values.
- If sending a new wrapper it returns the new.
- If sending a new wrapper with same attributes merge with the older.
closes #1278
=> Merge attributes with wrapper_options

lib/simple_form/components/html5.rb, test/inputs/required_test.rb
Addresses https://github.com/plataformatec/simple_form/issues/1380
Confirmed that it was caused by https://github.com/plataformatec/simple_form/commit/a280ba770f2cbfa88b05e26cf83247d5b6900139. The breaking change was that it started to override the required option with `false` whenever `SimpleForm.browser_validations` was false.
Happy to add a spec if you agree with the approach 😄
=> Do not ignore implicitly passed required option

.travis.yml, gemfiles/Gemfile.rails-5-0-stable, lib/simple_form/form_builder.rb, lib/simple_form/inputs/base.rb, test/form_builder/general_test.rb, test/support/models.rb
Another take to fix #1342, building on top of #1398.
We now favour the `ActiveModel::Type` API when available (Rails 5+), and still support the column objects from earlier versions. Our test models now implement the `type_for_attribute` API, but I discussed once with @rafaelfranca about adding an end to end test case based on ActiveRecord (+ sqlite) to provide better feedback on this integration.
=> Support the ActiveModel::Type API when available

lib/simple_form/form_builder.rb, test/support/models.rb
Per the docs, it is required to be a string:
http://api.rubyonrails.org/v5.0.0/classes/ActiveRecord/ModelSchema/ClassMethods.html#method-i-type_for_attribute
If you send a symbol, you will get an empty
ActiveRecord::Type::Value instance instead of the actual
column type you might have expected.
Since `f.input [attr]` can otherwise be invoked with
either a symbol or string, it seems important to
support both.
Fixes #1421
=> Ensure the arg sent to `type_for_attribute` is a string

lib/simple_form/inputs/boolean_input.rb, test/inputs/boolean_input_test.rb
At my job, we need to generate boolean checkboxes with different label classes, like so:
``` html
<label class='control'>
<input type='checkbox'>
Regular checkbox
</label>
<label class='control small'>
<input type='checkbox'>
Small checkbox
</label>
```
The `boolean_label_class` global option was added in #999, but this PR adds the ability to specify the `:boolean_label_class` on a per-input basis.
=> specify :boolean_label_class on a per-input basis

lib/simple_form/inputs/collection_input.rb
Fixnum and Bignum is deprecated at Ruby2.4.
https://github.com/ruby/ruby/blob/v2_4_0/NEWS#L288
=> remove Fixnum and Bignum deprecated warning

.travis.yml
Ruby 1.9.3 was end-of-lifed on 2015-02-23.
=> [TASK] Drop support for Ruby 1.9.x

.travis.yml
I don't know why but JRuby build is failing on Travis CI. The output:
```
3.73s$ rvm use jruby --install --binary --fuzzy
Unknown ruby string (do not know how to handle): jruby-9.1.14.0200.
Unknown ruby string (do not know how to handle): jruby-9.1.14.0200.
Unknown ruby string (do not know how to handle): jruby-9.1.14.0200.
Unknown ruby string (do not know how to handle): jruby-9.1.14.0200.
jruby-9.1.14.0200 is not installed - installing.
Unknown ruby string (do not know how to handle): jruby-9.1.14.0200.
Unknown ruby string (do not know how to handle): jruby-9.1.14.0200.
Unknown ruby string (do not know how to handle): jruby-9.1.14.0200.
Unknown ruby string (do not know how to handle): jruby-9.1.14.0200.
Searching for binary rubies, this might take some time.
Unknown ruby string (do not …
```
=> Fix JRuby build on Travis CI

lib/simple_form.rb
Hello, 
This PR should fix #1498. 
Usually you will have required `action_pack` before using `simple_form`, but sometimes that hasn't happened yet.
Please check it out and let me know what you think.
Thanks!
=> require 'action_pack' before using it

lib/simple_form/form_builder.rb, test/form_builder/association_test.rb, test/support/models.rb
This PR solves the issue  https://github.com/plataformatec/simple_form/issues/1519
As we are using the `instance_exec` to execute the scope from the association, when the scope has a parameter, it's breaking.
The scope's parameter always will be the instance of the own class, so we can fix it using the object instance that simple form uses to build the form.
=> Fix error when the scope from association has parameter

lib/simple_form/inputs/boolean_input.rb, test/inputs/boolean_input_test.rb
Rails does not generate a hidden field for checkboxes if
`unchecked_value` is false. The nested boolean creates its own hidden
field and ignores this rule from rails. That means that the hidden
field is generated for a falsey value when using the nested style, but
not when using the inline style.
This commit fixes this problem by making the nested style behave like
the inline style, adhering to the standard set by rails.
Resolves: #1320
Note that this may cause problem for people relying in this faulty behavior. But I think it's a good idea to fix this inconsistency in the long run.
=> Exclude hidden field when unchecked_value: false

lib/simple_form/form_builder.rb, test/form_builder/association_test.rb, test/form_builder/error_test.rb, test/form_builder/general_test.rb, test/form_builder/hint_test.rb, test/form_builder/label_test.rb, test/support/models.rb, test/test_helper.rb
SimpleForm expects `@object` will be ActiveRecord instance and trying to call
- `@object.send(attribute_name)`
- `@object.column_for_attribute(attribute_name)`
- `@object.class.reflect_on_association(association)`
In case we use decorated (presenter) object when passing to `simple_form_for` association input does not work as expected.
Idea is to follow `@object.to_model` convention when trying to interact with `@object` as ActiveRecord instance, like Rails does in [FormHelper](https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/form_helper.rb#L458) for example.
I will add tests if idea generally is OK.
=> Try convert @object to model in case we got decorated object

CHANGELOG.md, lib/simple_form/inputs/collection_check_boxes_input.rb, lib/simple_form/inputs/collection_radio_buttons_input.rb, test/inputs/collection_check_boxes_input_test.rb, test/inputs/collection_radio_buttons_input_test.rb
Simple Form is rendering the character value instead the non-string value when the input is radio or checkbox in boolean nested style and have a collection that the first item is a non-string value
When Simple Form is building the label tag, it concatenates the input HTML that is a string with the attribute from a collection that should be a string too. If it is not, it will convert the attribute to a character before concatenation.
The input generated by the collection_builder is a [ActiveSupport](http://api.rubyonrails.org/classes/ActiveSupport/SafeBuffer.html#method-i-2B) instance. So when the method `+` is called it's calling the [String#concat.](https://ruby-doc.org/core-1.9.2/String.html).
```bash
collection_builder.radio_button + 1
=> "<input class=\"radio_buttons \" …
```
=> Fix boolean inputs in nested style for label non-string

lib/generators/simple_form/templates/config/initializers/simple_form_foundation.rb
As mentioned in the issue #1339 (some years ago), the position for the labels when using the horizontal form class was wrong.
This PR fixes the label alignment problem by making the "right" class become "text-right". :slightly_smiling_face:
=> Fix horizontal form label position, from right to text-right

lib/simple_form/components/placeholders.rb
Similar to https://github.com/plataformatec/simple_form/pull/1086.
If we are using `placeholder_text` in custom wrapper within label tag it will cause deprecation warning. i.e:
``` [ruby]
config.wrappers :custom_wrapper, tag: "div", class: "form-group horizontal-group" do |b|
b.wrapper tag: "label", class: "col-sm-8 btn btn-default" do |lb|
lb.use :placeholder_text
lb.use :input, class: "hidden"
end
end
```
This is fix for deprecation warning.
=> silent deprication warning for placeholder_text

CHANGELOG.md, README.md, lib/generators/simple_form/templates/config/initializers/simple_form.rb, lib/simple_form/inputs/base.rb, test/form_builder/wrapper_test.rb, test/support/misc_helpers.rb
Allow custom errors classes to input in our wrappers. With it, when a validation happens, the input will be rendered with the error class defined in the wrapper.
We can configure an wrapper:
```ruby
config.wrappers :form, tag: 'div', class: 'field', error_class: 'invalid' do |b|
b.use :label
b.use :input, error_class: 'is-invalid'
end
```
And when a form with errors be rendered, will generated the follow markup:
```HTML
<div class="field invalid">
<input class="string required is-invalid" type="text" value="ok" name="user[name]" id="user_name">
</div>
```
Thank you @CharlieHawker by #1476 and #1475
=> Allow custom errors classes to inputs

CHANGELOG.md, README.md, lib/simple_form/form_builder.rb, test/form_builder/general_test.rb, test/support/models.rb
These are all commonly-used Postgres types. Fixes #1484 
@rafaelfranca I added tests but I'm concerned that they aren't actually accomplishing what they're supposed to. I tried using `uuid` as an example and deleted [the mapping](https://github.com/plataformatec/simple_form/blob/v3.5.0/lib/simple_form/form_builder.rb#L22) for that from `form_builder.rb` but the tests for it still passed. I believe that [test/support/models.rb](https://github.com/plataformatec/simple_form/blob/master/test/support/models.rb) might be responsible for the tests passing rather than the actual mapping from the gem. I'm a bit confused. However, this does work correctly in my application where I was using the previous workaround, so there's that.
=> Support for citext, hstore, json & jsonb columns

CHANGELOG.md, README.md, lib/generators/simple_form/templates/config/initializers/simple_form.rb, lib/generators/simple_form/templates/config/initializers/simple_form_bootstrap.rb, lib/generators/simple_form/templates/config/initializers/simple_form_foundation.rb, lib/simple_form.rb, test/components/custom_components_test.rb
Related to https://github.com/plataformatec/simple_form/issues/1176 and more discussion about it in https://github.com/plataformatec/simple_form/pull/1554
This is a public API to allow users register custom components without monkey patching Simple Form.
- Create your custom component.
```ruby
module InputGroup
def preprend
...
end
def append
...
end
end
SimpleForm.include_component(InputGroup)
```
- Tells to Simple Form  the place that the components will be
```ruby
Dir[Rails.root.join('lib/components/**/*.rb')].each { |f| require f }
```
- Use the custom component in some wrapper.
```ruby
SimpleForm.setup do |config|
config.wrappers :input_group, tag: :div, error_class: :error do |b|
b.use :label
b.optional :prepend
b.use :input
b.use :append
end
end
```
- Using wrapper with the custom …
=> Add API to register custom components

CHANGELOG.md, README.md, lib/generators/simple_form/templates/config/initializers/simple_form.rb, lib/generators/simple_form/templates/config/initializers/simple_form_bootstrap.rb, lib/generators/simple_form/templates/config/initializers/simple_form_foundation.rb, lib/simple_form.rb, lib/simple_form/components/errors.rb, lib/simple_form/wrappers/root.rb, test/form_builder/error_test.rb, test/form_builder/general_test.rb, test/form_builder/wrapper_test.rb, test/support/misc_helpers.rb
This just continues the great work started by @aeberlin with #1333 
---
The purpose of this PR is to improve style support for inputs with validations. Simply put, the lack of an applied `:error_class` is not indicative of the attribute being valid. While this isn't a guaranteed method of determining if it is valid, it is as close as programmatically possible (AFAIK). See caveats below.
When a `:valid_class` is specified, it will be applied to an input wrapper given the following conditions:
1. Object exists.
1. Object responds to `:errors`.
1. There are no validation errors (e.g. validations passed or were not specified).
1. Object responds to the attribute method.
1. Return value of attribute method is present.
1. Added `:valid_class` declarations (similar to those for `:error_class`) …
=> Add :valid_class on input wrapper when value is present and valid v2

CHANGELOG.md, README.md, lib/generators/simple_form/templates/config/initializers/simple_form.rb, lib/simple_form/inputs/base.rb, test/form_builder/wrapper_test.rb, test/support/misc_helpers.rb
This is just the consequent follow-up after https://github.com/plataformatec/simple_form/pull/1553 introduced valid_class on input wrapper.
* allow **valid class** to **inputs** if value is present & valid 💚 
* template and implementation pattern:
🔗 https://github.com/plataformatec/simple_form/pull/1552
Would add framework support for [Server Side Form](https://getbootstrap.com/docs/4.0/components/forms/#server-side) like Bootstrap. 
📺 [Demo App](https://simple-form-bootstrap4.herokuapp.com/examples/vertical)
=> allow valid class to inputs if value is present & valid

CHANGELOG.md, lib/generators/simple_form/templates/config/initializers/simple_form.rb, lib/generators/simple_form/templates/config/initializers/simple_form_bootstrap.rb, lib/generators/simple_form/templates/config/initializers/simple_form_foundation.rb, lib/simple_form.rb, lib/simple_form/form_builder.rb, test/form_builder/input_field_test.rb
This PR is similar to this one https://github.com/plataformatec/simple_form/pull/1552. It allows validation classes on `input_field`.
To get this work I added two configs for the Simple Form: `input_field_error_class` and `input_field_valid_class`. Once the user setup a class for these configs, the configured classes will be rendered according to the form validation.
- Setup the `input_field` classes.
```ruby
SimpleForm.setup do |config|
config.input_field_valid_class = 'is-valid'
config.input_field_error_class = 'is-invalid'
end
```
- Build the form.
```erb
<%= simple_form_for @product do |f| %>
<%= f.input_field :name %>
<div class="form-actions">
<%= f.button :submit %>
</div>
<% end %>
```
- When the validation happening, the input will be rendered with the validation classes.
```HTML …
```
=> Allow validation classes on input_field

lib/simple_form/components/labels.rb, test/components/label_test.rb
Since 3.1 it is possible to set a custom `i18n_scope`. This was not
respected to build the required html for label inputs.
=> Use custom i18n scope for label required html

lib/simple_form/form_builder.rb, test/form_builder/general_test.rb, test/support/models.rb
Match on word boundaries only.
The word "hourly" triggers a url type validation, that's not great.
=> Guess input type more carefully

lib/simple_form/form_builder.rb, test/form_builder/input_field_test.rb, test/inputs/disabled_test.rb, test/support/misc_helpers.rb
Allows individual options to be disabled instead of just the whole
select.
Fixes #1365.
=> Improve disabled option to input_field

lib/simple_form/components/errors.rb, test/form_builder/error_test.rb
This PR change the `has_errors?` method to allow custom errors on forms without a model:
```
= simple_form_for :user, url: users_path do |f|
= f.input :email, error: 'custom error'
```
```
...
<div class="form-group email optional user_email">
<label class="control-label email optional" for="user_email">Email</label>
<input class="form-control string email optional" type="email" name="user[email]" id="user_email">
</div>
...
```
```
= simple_form_for :user, url: users_path do |f|
= f.input :email, error: 'custom error'
```
```
<div class="form-group email optional user_email has-error">
<label class="control-label email optional" for="user_email">Email</label>
<input class="form-control string email optional" aria-invalid="true" type="email" name="user[email]" id="user_email">
<span …
```
=> Allow custom error on forms without model

lib/generators/simple_form/templates/config/initializers/simple_form.rb
config was removed in f67bdbb12255da21c4253bc492fda32337da664a
=> remove error_notification_id from generator template

test/inputs/discovery_test.rb, test/support/discovery_inputs.rb
A simple passing test to make sure you can remove classes from `input_html_classes` as well as add to them.
Creating this pull request to accompany an issue I created: #1602.
=> Add test to make sure you can remove default classes in custom inputs

CHANGELOG.md, lib/simple_form/inputs/base.rb, test/inputs/discovery_test.rb
Fixes: #1604. `input_html_classes` is a function therefore calling it multiple times will run the function multiple times.
This pull request stores the return value of `input_html_classes` in a variable so that it is called only once. That variable can then be used instead.
=> Memoize input_html_classes

lib/generators/simple_form/templates/config/initializers/simple_form_bootstrap.rb
Removes the class (`.form-control-label`) that were removed from bootstrap in vertical form layouts and renames with `.col-form-label` in horizontal form layouts. 
https://getbootstrap.com/docs/4.1/migration/
> Removed the unused `.form-control-label class`. If you did make use of this class, it was duplicate of the `.col-form-label` class that vertically centered a `<label>` with it’s associated input in horizontal form layouts.
> Renamed `.control-label` to `.col-form-label`.
=> Removes or renames label classes

CHANGELOG.md, README.md, lib/simple_form/tags.rb, test/inputs/collection_check_boxes_input_test.rb, test/inputs/collection_radio_buttons_input_test.rb
Fix https://github.com/plataformatec/simple_form/issues/1628 and related to https://github.com/plataformatec/simple_form/pull/1369
Simple Form already supports label custom classes for checkboxes / radio buttons when they have nested style. This commit allows this feature if they are inline as well.
cc @m5o
=> Support to label custom classes for inline checkboxes and radio buttons

CHANGELOG.md, lib/generators/simple_form/templates/config/initializers/simple_form_bootstrap.rb
* update bootstrap template to match `v4.1.3`
* https://getbootstrap.com/docs/4.1
---
* add item_label_class for for radio buttons and check boxes collection
* :link: https://github.com/rafaelfranca/simple_form-bootstrap/pull/95
* remove unused .form-control-label css class
* :link: https://github.com/rafaelfranca/simple_form-bootstrap/pull/97
=> update bootstrap template to match v4.1.3

CHANGELOG.md, lib/generators/simple_form/templates/config/initializers/simple_form_bootstrap.rb
* minor refinements bootstrap `v4.3.1` with floating labels
:link: https://github.com/rafaelfranca/simple_form-bootstrap/pull/103
=> refinements for bootstrap v4.3.1

README.md
Hello,
The commit https://github.com/plataformatec/simple_form/commit/d1ff0b11a48172dc85df409d0d270732ada011b9 introduced this text, and the https://github.com/plataformatec/simple_form/commit/caca9457266fdbc8243c2b9ba8de37e64409c58a forgot to remove some of the text when it was updated.
This dead text has been there a while :sweat_smile:
=> Remove dead documentation

lib/simple_form/inputs/priority_input.rb, test/inputs/priority_input_test.rb
Don't overwrite `#has_required?` in `PriorityInput`, let that input inherit behavior.
Properly close #1355.
Properly close #866.
Continuation of #373 that closed #340.
Undoes some of, very old, outdated, #141.
=> Allow "required" attribute in generated select elements of PriorityInput

simple_form.gemspec
The RubyGems property rubyforge_project is removed without a replacement.
=> Gemspec: Drop EOL'd property rubyforge_project

.travis.yml, test/action_view_extensions/builder_test.rb, test/form_builder/wrapper_test.rb, test/support/models.rb
After we changed the default build to run on Rails 6 (https://github.com/plataformatec/simple_form/commit/fc25ab40a28ad477e1ac0e45ddcf7ad2b64891f3) the tests started failing. This pull request fixes them.
See the commit messages for more details of why each change was done.
=> Fix tests on Rails 6

CHANGELOG.md, lib/simple_form/form_builder.rb, test/form_builder/general_test.rb, test/support/models.rb
As reported in https://github.com/plataformatec/simple_form/issues/1671, the method with suffix `_url` is likely to cause false positives. By using the alternative `remote_url` we might be able to make wrong assumptions, although they're still possible.
Fixes https://github.com/plataformatec/simple_form/issues/1671
=> Replace `_url` with `remote_url`

lib/simple_form/inputs/collection_input.rb, test/inputs/collection_select_input_test.rb
When the prompt was set, example: `- please select an option -`, the value generated for the `aria-required` field value was the same as the prompt.
The value of aria-required should be always a boolean.
Before:
After:
=> Fix 'aria-required' field generated by prompt

.travis.yml, Gemfile.lock
This commit is supposed to fix the following error on Travis:
```
4: from /home/travis/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
3: from /home/travis/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
2: from /home/travis/.rvm/rubies/ruby-2.6.3/bin/bundle:23:in `<main>'
1: from /home/travis/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems.rb:294:in `activate_bin_path'
/home/travis/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems.rb:275:in `find_spec_for_exe':
Could not find 'bundler' (1.17.3) required by your /home/travis/build/plataformatec/simple_form/Gemfile.lock.
(Gem::GemNotFoundException)
```
Ref: https://github.com/bundler/bundler/issues/6882#issuecomment-469858087
Also, the CI can no longer build for jruby 9.1.17.0 due this error:
``` …
```
=> Fix Travis CI

lib/generators/simple_form/templates/README
This PR changes the console output that is shown when the installer is invoked with the --bootstrap option
```
rails generate simple_form:install --bootstrap
```
The previous instruction was a bit confusing, as form-inline is only one of the many possible classes that can be used. It’s also (probably) not the one that is most often used, so mentioning it in the installation output implies that it’s more significant than it actually is.
The sentence was also imperative:
Inside your views, use the 'simple_form_for' with the Bootstrap form class, ‘.form-inline’
BEFORE
```
===============================================================================
Be sure to have a copy of the Bootstrap stylesheet available on your
application, you can get it on http://getbootstrap.com/.
Inside your …
```
=> Remove instruction to use form-inline class

lib/simple_form/form_builder.rb, lib/simple_form/inputs.rb, lib/simple_form/inputs/rich_text_area_input.rb, test/inputs/rich_text_area_input_test.rb
For #1638 I've added the appropriate input. 
I've also added a test that passes, but I'm not familiar enough with the rich_text_area in Rails to know what else I should be testing for: feedback appreciated!
I've tested this on a project in development and it seems to work nicely, but I haven't tried adding any optional attributes, so might be worth exploring
=> Added RichTextAreaInput for ActionText

lib/simple_form/wrappers/root.rb, test/form_builder/wrapper_test.rb, test/support/misc_helpers.rb
https://github.com/plataformatec/simple_form/issues/1656
Previously, we would check for validity all the time, even if the outcome of the check added no class. This meant that there was no way to opt out of the check in cases where it was expensive (if the file is stored in S3, in our example).
Now, we only check for validity if there is a valid_class defined to be added if the field is valid.
=> Skip valid_class check if no class defined

lib/simple_form/components/maxlength.rb, lib/simple_form/components/minlength.rb
Validation with a tokenizer was only supported for versions of Rails
less than 5. As noted [here](https://github.com/heartcombo/simple_form/blob/v3.5.1/lib/simple_form/components/maxlength.rb#L31-L32)
When [Rails 4 support was dropped](https://github.com/heartcombo/simple_form/commit/ffc13c9925da957c274c1f090f7fc80b65fda307), the use of the `has_tokenizer?` method is
no longer used anywhere in the project. These changes remove the unused
methods.
=> Remove unused methods

README.md
Use direct heroku url since CNAME config doesn’t work anymore
=> update bootstrap example app url

lib/simple_form/inputs/boolean_input.rb
Returning a normal string here would result in raw html displaying on the final page, instead of the actual form. This fix ensure a ActiveSupport::SafeBuffer
=> fix build_hidden_field_for_checkbox not returning ActiveSupport::SafeBuffer instance.

README.md, lib/generators/simple_form/install_generator.rb, lib/generators/simple_form/templates/config/initializers/simple_form_bootstrap.rb
This syncs up the generator template with the new one from `simple_form-bootstrap`.
There's a minor issue with the [styling of validation errors in input groups](https://github.com/heartcombo/simple_form-bootstrap/pull/334) that I'd like to look at, but I don't think we need to wait for that before merging this in.
/cc @m5o
=> Update install generator for Bootstrap 5

lib/simple_form/form_builder.rb
Calling `where` with a nil argument is not supported in [mongoid](https://github.com/mongodb/mongoid/blob/5c90efb00347e25d8b5ff0ce27d00ac8c906f0e2/lib/mongoid/criteria/queryable/selectable.rb#L795) and throws an error.
Calling `where` only if there are any conditions fixes this issue and seems to me a straightforward change.
The question is if there are cases where you want to call `where` with a nil argument?
=> Only call where if needed

CHANGELOG.md, lib/simple_form/inputs/grouped_collection_select_input.rb, test/inputs/grouped_collection_select_input_test.rb
Since Rails v5.2, the group method could be a callable object.
=> Allow proc as group_method for grouped collection select

lib/simple_form/inputs/boolean_input.rb, test/inputs/boolean_input_test.rb
On `nested`-style boolean inputs, it's possible to opt-out of the hidden input
generation by passing the `include_hidden: false` option.
However, for `inline` inputs, this still generates the hidden field, causing
an inconsistency between the two boolean styles, and a whole lot of late night confusion.
A workaround has been proposed in [a comment from 2016](https://github.com/heartcombo/simple_form/issues/1377#issuecomment-227616280),
which consists in passing `include_hidden` in the `input_html`. I think this is 
not ideal, as it causes inconsitencies between the APIs of the boolean styles.
This PR makes the inline checkboxes honor the `include_hidden` styles, making their API consistent.
=> Honor `include_hidden` on inline boolean inputs

README.md
Use the correct default branch on Rubydoc links.
=> Fix broken Rubydoc links in README.md

lib/simple_form/form_builder.rb
The `FormBuilder#find_mapping` method is relying on `Object#const_get` raising an exception if the constant doesn't exist, rather than directly checking if it exists with `Object#const_defined?`.
Exceptions are slow due to generating backtraces - and then when other debugging gems (such as did_you mean, which are included with Ruby and Rails these days) get involved it resulted in excessive Object allocation.
Normally the `discovery_cache` would mitigate this, so there wouldn't be many calls to `#mapping_override`, however when you use `#simple_fields_for` with a collection/has_many association the cache is empty for each item in the collection.
Before this change this code was taking approximately 2 seconds and 2.9million allocations for 235 records:
```
<%= f.simple_fields_for …
```
=> Speed up nested #simple_fields_for usage by a considerable amount

lib/simple_form/inputs/rich_text_area_input.rb
Trix (the rich text editor that's rendered by Action View's form builder) has supported the `[placeholder]` attribute since at least version [0.9.0][] (and continues to support it in [2.1.1][].
This commit enables `:placeholder` support in the
`SimpleForm::Inputs::RichTextAreaInput` class to transform placeholder internationalization strings into `trix-editor[placeholder]` HTML attributes.
[0.9.0]: https://github.com/basecamp/trix/tree/0.9.0?tab=readme-ov-file#creating-an-editor
[2.1.1]: https://github.com/basecamp/trix/tree/v2.1.1?tab=readme-ov-file#creating-an-editor
=> Integrate `:rich_text_area` with placeholders

README.md
SimpleForm relies on `has_attribute?` and `type_for_attribute` to infer attribute type so it may generate the correct input type according to its mapping.
I am currently trying to improve Ransack / SimpleForm integration at PR https://github.com/activerecord-hackery/ransack/pull/1487
It was a little hard to me to guess how this was done internally.
I wish I've had seen issue #1666 before.
This PR aims to improve the documentation regarding the use of SimpleForm with non-ActiveRecord objects, making it easier for others to implement and understand.
To ensure the documentation's correctness I am also providing a sample test of the example code.
```ruby
require "bundler/inline"
gemfile(true) do
source "https://rubygems.org"
gem "rails"
gem "sqlite3"
gem "simple_form"
gem "byebug"
end
require …
```
=> Improve docs on Non Active Record

lib/simple_form/components/labels.rb
When discovering translations, Rails [passes the `base` object to `human_attribute_name`](https://github.com/rails/rails/blob/af09d6b90b23c2d7389f879f37e9cbbeea078e5a/activemodel/lib/active_model/error.rb#L55). This is helpful because `human_attribute_name` is a class method and does not have access to instance methods. If someone wants to customize the behavior of said method based on properties of the instance, this is not possible without this argument. This merge request makes a tiny change to pass this base object.
=> Pass base object to `human_attribute_name` for labels

lib/simple_form/form_builder.rb
This PR fixes a bug introduced by ActiveRecord::Encrypted attributes. 
Instead of returning a `ActiveModel::Type::String` like they used to, encrypted attributes return an instance of `ActiveRecord::Encryption::EncryptedAttributeType`, on which you need to call `#cast_type` in order to obtain the original type. 
To fix this, I check whether or not the attribute `#responds_to?(:cast_type)` which would indicate that we need to take into account the underlying type instead of just `#type_for_attribute`.
Checking this instead of checking if the `attribute_name` `#responds_to?(:encrypted_attributes)` allows to take into account other forms of type overriding that ActiveRecord may introduce in the future or potentially already exist. 
See the type difference below between a regular string …
=> Fix encrypted attributes improperly casted
