- lib/simple_form/form_builder.rb
For details, see issue https://github.com/plataformatec/simple_form/issues/1245
> Add map_type for Hidden input

- README.md
> ~ Add doc for option `selected` to README

- README.md
I added a precision for the error overwrite as I had looked for it for several minutes in vain.
> Precising error: in Readme

- README.md
Makes the README a bit clearer on when fields are required vs optional. Addresses https://github.com/plataformatec/simple_form/issues/1408
> Clarify docs about required attribute behavior

- .gitignore
- lib/generators/simple_form/templates/config/initializers/simple_form.rb
- lib/generators/simple_form/templates/config/initializers/simple_form_bootstrap.rb
- lib/generators/simple_form/templates/config/initializers/simple_form_foundation.rb
- lib/simple_form.rb
- lib/simple_form/components.rb
- lib/simple_form/components/minlength.rb
- lib/simple_form/form_builder.rb
- lib/simple_form/inputs/base.rb
- lib/simple_form/inputs/password_input.rb
- lib/simple_form/inputs/string_input.rb
- lib/simple_form/inputs/text_input.rb
- test/form_builder/input_field_test.rb
- test/inputs/string_input_test.rb
- test/inputs/text_input_test.rb
- test/support/models.rb
- test/test_helper.rb
Hi,
I did this for some hack days at work (powershop.co.nz).
AFAICT, the only thing that's off is the .gitignore on the RubyMine project folder - sorry about that, I've run out of time to rewrite the commits.
Cheers, love your work,
Seth
> Added Minlength validation with tests a la Maxlength

- README.md
Changes made to lines 217 and 1060 as per Issue [#1468](https://github.com/plataformatec/simple_form/issues/1468) (two typo edit suggestions)
@nashby thanks for the clarification and understanding in regard to my beginner mistake. 👍
> Fix grammar errors (correct PR)

- README.md
For some reason, the table was indented as a code block
> render an actual table in the readme

- lib/simple_form.rb
Hello, 
This PR fixes #1503 by making the condition more specific. 
Please check it out and let me know if you have any comments.
Thanks!
> Check if Rails.env is defined

- lib/simple_form/form_builder.rb
- test/form_builder/association_test.rb
- test/support/models.rb
A reimplementation of  #1351 that includes tests.
:pear: @christian314159
> Only call `where` on associations when they respond to it.

- CHANGELOG.md
This just updates the unreleased section with the last changes.
> Update changelog [ci skip]

- lib/simple_form/components/minlength.rb
> Fix minlength

- lib/simple_form/components/errors.rb
> Make errors_on_attribute return [] when not present

- README.md
As we can make explicit the `label_method` and `value_method` when we are using the collection as radio buttons or check boxes, I'm adding docs to exemplify how to do it.
> Improve collections docs [ci skip]

- CHANGELOG.md
- README.md
These updates are about using Simple Form with non Active Record objects.
More information: https://github.com/plataformatec/simple_form/issues/1549
> Update README and CHANGELOG about updates 3.5.1

- lib/generators/simple_form/templates/_form.html.erb
- lib/generators/simple_form/templates/_form.html.haml
- lib/generators/simple_form/templates/_form.html.slim
> Add base error display alongside existing errors

- lib/generators/simple_form/templates/config/initializers/simple_form.rb
Add missing comma, between the names of the methods #1577.
> Add missing comma

- lib/simple_form/inputs/string_input.rb
> Fix column type citext HTML5 input type bug

- .travis.yml
- CHANGELOG.md
- test/inputs/datetime_input_test.rb
- test/inputs/priority_input_test.rb
- test/inputs/string_input_test.rb
- test/support/models.rb
Remove old versions of ruby from CI
Remove some old checks for Rails < 5
> Drop EOL Ruby versions

- MIT-LICENSE
- README.md
Signed-off-by: Atul Bhosale <atul1bhosale@gmail.com>
> Update copyright notice to 2019 [ci skip]

- lib/simple_form/form_builder.rb
- test/form_builder/general_test.rb
- test/support/models.rb
Closes https://github.com/heartcombo/simple_form/issues/1696
> Fix for ActiveStorage::Attached::Many

- README.md
Maybe you want to remove completely this sentence.
> Update version number on README

- README.md
Added explanation on how to customize the hint class.
> Explanation on how to customize the hint class.

- lib/generators/simple_form/templates/config/initializers/simple_form_bootstrap.rb
* remove a misleading sentence
* `Please do not make direct changes to this file!`
* 💭 prep & discussion:
* https://github.com/heartcombo/simple_form-bootstrap/pull/359
fixes #1756
/cc @carlosantoniodasilva @collimarco
> Update bootstrap initializer banner

- README.md
Addresses issue #1780. 
Two commits:
* simple string change
* new comment clarifying the handling of hidden field on check boxes
> Revise unchecked docs

- simple_form.gemspec
There are several files in the gem package that aren't useful for downstream projects. Removing these reduces the gem package size from **83K** to **50K**!
<details><summary>gem contents diff</summary>
```diff
CHANGELOG.md
MIT-LICENSE
README.md
lib/generators/simple_form/USAGE
lib/generators/simple_form/install_generator.rb
lib/generators/simple_form/templates/README
lib/generators/simple_form/templates/_form.html.erb
lib/generators/simple_form/templates/_form.html.haml
lib/generators/simple_form/templates/_form.html.slim
lib/generators/simple_form/templates/config/initializers/simple_form.rb
lib/generators/simple_form/templates/config/initializers/simple_form_bootstrap.rb
lib/generators/simple_form/templates/config/initializers/simple_form_foundation.rb …
```
> Remove test files from the gem package

- CHANGELOG.md
- README.md
- lib/simple_form/inputs.rb
- lib/simple_form/inputs/weekday_input.rb
- test/inputs/weekday_input_test.rb
Closes https://github.com/heartcombo/simple_form/issues/1770
> Add weekday select input.
